# Site settings
title: Fluxos Iamspe
email: censomedicoiamspe@gmail.com
description: |
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# Build settings
theme: minima
plugins:
  - github-pages
  - jekyll-feed
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-spaceship

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md
  - LICENSE.md
