# Site settings
title: Fluxos Iamspe
email: censomedicoiamspe@gmail.com
repository: Nereare/fluxos

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-spaceship
# Spaceship settings
jekyll-spaceship:
  processors:
    - table-processor
    - mermaid-processor
    - emoji-processor
  mermaid-processor:
    mode: default
    syntax:
      code: 'mermaid'
# Theme settings
search_enabled: true
aux_links:
  "Modelos Pront":
    - 'https://pront.padoim.com'
  "Problemas":
    - 'https://github.com/Nereare/fluxos/issues'
## Footer
### last edited timestamp
last_edit_timestamp: true
last_edit_time_format: '%d/%m/%Y %R'
### Page edition message
gh_edit_link: true
gh_edit_link_text: "Editar o conteúdo desta página..."
## Callouts
callouts:
  warning:
    title: Perigo
    color: red

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md
  - LICENSE.md
