# Site settings
title: Fluxos Iamspe
email: censomedicoiamspe@gmail.com
repository: Nereare/fluxos

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-spaceship
# Spaceship settings
jekyll-spaceship:
  processors:
    - table-processor
    - mathjax-processor
    - mermaid-processor
    - emoji-processor
  mermaid-processor:
    mode: default
    syntax:
      code: 'mermaid'
# Theme settings
## Icon
logo: /assets/iamspe.png
favicon_ico: /assets/iamspe.ico
## Navigation
heading_anchors: true
search_enabled: true
aux_links:
  "Modelos Pront":
    - 'https://pront.padoim.com'
  "Problemas":
    - 'https://github.com/Nereare/fluxos/issues'
## Back to top button
back_to_top: true
back_to_top_text: "Começo"
## Callouts
callouts:
  danger:
    title: Perigo
    color: red
  warning:
    title: Importante
    color: yellow
  info:
    title: Lembre-se
    color: blue
  note:
    title: Observação
    color: green

# Defaults
defaults:
  - scope:
      path: "" # I.e. all files
    values:
      layout: "default"

# Exclusions
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md
  - LICENSE.md
